FROM ubuntu:latest
MAINTAINER Luke Nimtz <luke.nimtz@gmail.com>

RUN apt-get update && apt-get install -y\
  vim-nox\
  git

ADD .vimrc /root/.vimrc
ADD http://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim\
  /root/.vim/autoload/
ADD http://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim\
  /root/.vim/colors/

RUN vim +PlugInstall +qall

# cpy bins for dist
RUN mkdir /root/bin/
RUN cp /usr/bin/vim /root/bin/
RUN cp /bin/sh /root/bin/
RUN cp /usr/bin/stat /root/bin/
