version: "2"
services:
  devbox:
    build: .
    volumes:
      - $HOME/code/:/home/lukenimtz/code/
      - ssh-agent:/var/run/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/var/run/ssh-agent/auth/sock


volumes:
  ssh-agent:
    external: true
