FROM c12e/alpine-glibc
MAINTAINER Luke Nimtz <luke.nimtz@gmail.com>

ADD bin/stat /usr/bin/
ADD bin/sh /bin/

ADD bin/vim /usr/bin/
ADD .vim/* /root/.vim/
ADD .vimrc /root/
ADD .viminfo /root/

WORKDIR /root/
# ENTRYPOINT /usr/bin/vim