version: "2"
services:
  devbox:
    build: .
    volumes:
      - devbox-home:$HOME
      - $HOME/.ssh:$HOME/.ssh
      - $HOME/code:$HOME/code
      - ssh-agent:/var/run/ssh-agent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SSH_AUTH_SOCK=/var/run/ssh-agent/auth/sock

volumes:
  devbox-home:
  ssh-agent:
    external: true
